window.BB=window.BB||{};
(()=>{'use strict';const $=s=>document.querySelector(s);BB.quality=localStorage.getItem('bb-quality')||'high';let storyPage=0,storyData=null,storyDone=null,last=performance.now(),lastDraw=0;
BB.beginLevel=function(g){BB.game=g;BB.Input.clear();BB.particles=[];BB.texts=[];BB.shake=0;BB.flash=0;$('#menu').hidden=true;$('#story').hidden=true;$('#game').hidden=false;BB.UI.hideOverlay();BB.Audio.musicFor(g.level,g.level%5===0);last=performance.now();BB.UI.sync();};
function showStory(level,done){storyData=BOMBER_STORY[level]||BOMBER_STORY.default;storyPage=0;storyDone=done;$('#menu').hidden=true;$('#game').hidden=true;$('#story').hidden=false;$('#storyChapter').textContent=`CAPÍTULO ${level}`;$('#storyTitle').textContent=storyData.title;renderStory();}
function renderStory(){const p=storyData.pages[storyPage];$('#storySpeaker').textContent=p.speaker;$('#storyText').textContent=p.text;$('#storyPage').textContent=`${storyPage+1} / ${storyData.pages.length}`;$('#storyNext').textContent=storyPage===storyData.pages.length-1?'INICIAR FASE →':'CONTINUAR →';}
function nextStory(){if(storyPage<storyData.pages.length-1){storyPage++;renderStory();}else closeStory();}function closeStory(){const d=storyDone;storyDone=null;$('#story').hidden=true;if(d)d();}
function start(){const level=BB.clamp(Number($('#levelSelect').value)||1,1,BB.MAX_LEVEL);showStory(level,()=>BB.beginLevel(BB.makeGame(level)));}
BB.finish=function(status){const g=BB.game;if(!g)return;g.status=status;BB.Input.clear();if(status!=='paused'){const unlocked=status==='won'?Math.min(BB.MAX_LEVEL,g.level+1):status==='completed'?BB.MAX_LEVEL:g.level,record=Math.max(+localStorage.getItem('bb-record')||0,g.score),best=Math.max(+localStorage.getItem('bb-level')||1,unlocked);localStorage.setItem('bb-record',record);localStorage.setItem('bb-level',best);BB.UI.populateLevels();}if(status==='won'||status==='completed'){BB.Audio.play('win');BB.Audio.stopMusic();}if(status==='gameover')BB.Audio.stopMusic();BB.UI.overlay(status==='completed'?'HISTÓRIA CONCLUÍDA':status==='won'?'PORTAL CONQUISTADO':status==='paused'?'JOGO PAUSADO':'FIM DE JOGO',status==='completed'?'O REI DO VAZIO CAIU!':status==='won'?`FASE ${g.level} COMPLETA!`:status==='paused'?'PAUSA':'GAME OVER',`${g.score} PONTOS${g.lastReward?` · ${g.lastReward}`:''}`,status==='completed'?'JOGAR NOVAMENTE':status==='won'?'PRÓXIMA FASE':status==='paused'?'CONTINUAR':'JOGAR DE NOVO');};
function primary(){const g=BB.game;if(!g)return start();if(g.status==='won'){const level=g.level+1,carry={lives:g.lives,score:g.score,range:g.range,maxBombs:g.maxBombs,speedLevel:g.speedLevel,shield:g.shield,nova:g.nova,remote:g.remote,pierce:g.pierce,fast:g.fast,giant:g.giant,kick:g.kick,glove:g.glove};showStory(level,()=>BB.beginLevel(BB.makeGame(level,carry)));}else if(g.status==='completed'){$('#levelSelect').value='1';start();}else if(g.status==='paused'){g.status='playing';last=performance.now();BB.UI.hideOverlay();BB.Audio.musicFor(g.level,g.level%5===0);}else start();}
function pause(){const g=BB.game;if(!g||!['playing','paused'].includes(g.status))return;if(g.status==='playing'){g.status='paused';BB.Input.clear();BB.Audio.stopMusic();BB.UI.overlay('JOGO PAUSADO','PAUSA',`${g.score} PONTOS`,'CONTINUAR');}else primary();}
function loop(now){const dt=Math.min(100,now-last||16);last=now;BB.update(dt);const interval=BB.quality==='low'?33:BB.quality==='medium'?20:0;if(!interval||now-lastDraw>=interval){BB.Render.draw(now);lastDraw=now;}requestAnimationFrame(loop);}
BB.Audio.init();BB.Render.init();BB.UI.populateLevels();BB.UI.setQuality(BB.quality);BB.UI.syncSound();$('#record').textContent=localStorage.getItem('bb-record')||0;$('#bestLevel').textContent=localStorage.getItem('bb-level')||1;
document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{BB.difficulty=b.dataset.diff;document.querySelectorAll('[data-diff]').forEach(o=>o.classList.toggle('selected',o===b));});document.querySelectorAll('[data-quality]').forEach(b=>b.onclick=()=>BB.UI.setQuality(b.dataset.quality));document.querySelectorAll('[data-mobile]').forEach(b=>b.onclick=()=>{document.body.dataset.mobile=b.dataset.mobile;localStorage.setItem('bb-mobile',b.dataset.mobile);document.querySelectorAll('[data-mobile]').forEach(o=>o.classList.toggle('selected',o===b));});document.body.dataset.mobile=localStorage.getItem('bb-mobile')||'normal';document.querySelectorAll('[data-mobile]').forEach(b=>b.classList.toggle('selected',b.dataset.mobile===document.body.dataset.mobile));document.querySelectorAll('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();BB.Input.press(b.dataset.dir,true)});['pointerup','pointerleave','pointercancel'].forEach(n=>b.addEventListener(n,()=>BB.Input.press(b.dataset.dir,false)));});
const map={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};addEventListener('keydown',e=>{if(map[e.key]){e.preventDefault();BB.Input.press(map[e.key],true);}if(e.key===' '){e.preventDefault();BB.putBomb();}if(e.key.toLowerCase()==='q')BB.remoteDetonate();if(e.key.toLowerCase()==='e')BB.throwBomb();if(e.key.toLowerCase()==='p'||e.key==='Escape')pause();if(e.key.toLowerCase()==='r')BB.restartLevel();});addEventListener('keyup',e=>{if(map[e.key])BB.Input.press(map[e.key],false)});addEventListener('blur',()=>BB.Input.clear());
$('#play').onclick=start;$('#storyNext').onclick=nextStory;$('#storySkip').onclick=closeStory;$('#sound').onclick=()=>BB.Audio.toggle();$('#mute').onclick=()=>BB.Audio.toggle();$('#back').onclick=()=>BB.UI.showMenu();$('#pause').onclick=pause;$('#bombButton').onpointerdown=e=>{e.preventDefault();BB.putBomb()};$('#remoteButton').onclick=()=>BB.remoteDetonate();$('#throwButton').onclick=()=>BB.throwBomb();$('#primary').onclick=primary;$('#overlayMenu').onclick=()=>BB.UI.showMenu();requestAnimationFrame(loop);})();
