window.BB=window.BB||{};
BB.AI={
  neighbors(x,y,kind=''){return Object.entries(BB.DIRS).map(([name,[dx,dy]])=>({name,x:x+dx,y:y+dy,dx,dy})).filter(p=>BB.walkable(p.x,p.y,kind,'enemy'))},
  dangerMap(horizon=1200){const g=BB.game,map=new Map();if(!g)return map;for(const f of g.blasts)map.set(BB.key(f),0);for(const h of g.hazards)map.set(BB.key(h),Math.min(map.get(BB.key(h))??Infinity,h.ttl));const bombs=[...g.bombs].sort((a,b)=>a.timer-b.timer);const trigger=new Map(bombs.map(b=>[b.id,b.timer]));for(let pass=0;pass<3;pass++)for(const b of bombs){const time=trigger.get(b.id);for(const t of BB.blastRay(b)){const k=BB.key(t);if(time<=horizon)map.set(k,Math.min(map.get(k)??Infinity,time));for(const other of bombs)if(other.id!==b.id&&BB.same(t,other)&&trigger.get(other.id)>time)trigger.set(other.id,time)}}return map},
  bfs(start,target,kind='',danger=null,max=120){const q=[start],prev=new Map(),seen=new Set([BB.key(start)]);let end=null,steps=0;while(q.length&&steps++<max){const cur=q.shift();if(cur.x===target.x&&cur.y===target.y){end=cur;break}for(const n of this.neighbors(cur.x,cur.y,kind)){const k=BB.key(n);if(seen.has(k))continue;if(danger?.has(k))continue;seen.add(k);prev.set(k,{from:BB.key(cur),node:n});q.push(n)}}if(!end)return null;let k=BB.key(end),node=end,path=[];while(k!==BB.key(start)){path.unshift(node);const rec=prev.get(k);if(!rec)break;k=rec.from;node={x:+k.split(',')[0],y:+k.split(',')[1]}}return path},
  safeEscape(e,horizon){const dm=this.dangerMap(horizon),danger=new Set([...dm.entries()].filter(([,t])=>t<=horizon).map(([k])=>k));if(!danger.has(BB.key(e)))return null;const candidates=[];for(let y=1;y<BB.ROWS-1;y++)for(let x=1;x<BB.COLS-1;x++){const k=`${x},${y}`;if(!danger.has(k)&&BB.walkable(x,y,e.kind,'enemy'))candidates.push({x,y})}candidates.sort((a,b)=>(Math.abs(a.x-e.x)+Math.abs(a.y-e.y))-(Math.abs(b.x-e.x)+Math.abs(b.y-e.y)));for(const t of candidates.slice(0,16)){const p=this.bfs(e,t,e.kind,danger,80);if(p?.length)return p[0]}return null},
  choose(e){const g=BB.game,cfg=BB.CONFIG[BB.difficulty],h=cfg.dangerHorizon;const escape=this.safeEscape(e,h);if(escape)return{...escape,state:'flee'};const opts=this.neighbors(e.x,e.y,e.kind);if(!opts.length)return null;if(cfg.ai==='weak'){const p=opts[Math.floor(Math.random()*opts.length)];return{...p,state:'wander'}};const target=cfg.ai==='smart'?BB.predictPlayer():g.player;if(cfg.ai==='normal'&&Math.random()>.72){const p=opts[Math.floor(Math.random()*opts.length)];return{...p,state:'patrol'}};const dangerMap=this.dangerMap(h),danger=new Set([...dangerMap.entries()].filter(([,t])=>t<=h).map(([k])=>k));const path=this.bfs(e,target,e.kind,danger,140);if(path?.length)return{...path[0],state:'chase'};opts.sort((a,b)=>(Math.abs(a.x-target.x)+Math.abs(a.y-target.y))-(Math.abs(b.x-target.x)+Math.abs(b.y-target.y)));return{...opts[0],state:'chase'}},
  canBombSafely(e){const g=BB.game,cfg=BB.CONFIG[BB.difficulty];const fake={x:e.x,y:e.y,range:2,timer:1000,id:-999,owner:'enemy'};g.bombs.push(fake);const safe=!!this.safeEscape(e,Math.max(1100,cfg.dangerHorizon));g.bombs.pop();return safe}
};
