window.BB=window.BB||{};
BB.UI={
  $(s){return document.querySelector(s)},
  syncSound(){const on=BB.Audio.sound;const sound=this.$('#sound'),mute=this.$('#mute');if(sound)sound.textContent=on?'🔊':'🔇';if(mute)mute.textContent=on?'♪':'×'},
  populateLevels(){const s=this.$('#levelSelect'),u=BB.clamp(BB.Save?.get('progress.bestLevel',1)||1,1,BB.MAX_LEVEL),cur=Number(s?.value)||1;if(!s)return;s.innerHTML='';for(let l=1;l<=u;l++){const o=document.createElement('option'),r=BB.Save?.get(`progress.ranks.${l}`,null);o.value=l;o.textContent=`Fase ${l}${l%5===0?' — CHEFE':''}${r?.grade?` · ${r.grade}`:''}`;s.appendChild(o)}s.value=String(Math.min(cur,u));this.renderWorldMap()},
  renderWorldMap(){const box=this.$('#worldMap');if(!box)return;const unlocked=BB.clamp(BB.Save?.get('progress.bestLevel',1)||1,1,BB.MAX_LEVEL),selected=Number(this.$('#levelSelect')?.value)||1;box.innerHTML='';for(let l=1;l<=BB.MAX_LEVEL;l++){const b=document.createElement('button'),r=BB.Save?.get(`progress.ranks.${l}`,null);b.type='button';b.innerHTML=`${l%5===0?'★ ':''}${l}${r?.grade?`<span class="rank-badge">${r.grade}</span>`:''}`;b.disabled=l>unlocked;b.className=`${l<=unlocked?'unlocked ':''}${l===selected?'selected ':''}${l%5===0?'boss':''}`;b.title=`${BB.THEMES[BB.worldIndex(l)]} · ${BB.levelDef(l).label}${r?` · Melhor ${r.grade} · ${r.score} pts`:''}`;b.onclick=()=>{this.$('#levelSelect').value=String(l);this.renderWorldMap()};box.appendChild(b)}},
  sync(){const g=BB.game;if(!g)return;this.$('#level').textContent=g.level;this.$('#lives').textContent='♥'.repeat(g.lives);this.$('#score').textContent=String(g.score).padStart(5,'0');const sec=Math.ceil(g.time/1000);this.$('#time').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;this.$('#time').style.color=sec<=30?'#ff5578':'';this.$('#theme').textContent=g.level%5===0?`⚠ ${BB.BOSS_NAMES[BB.worldIndex(g.level)]}`:BB.THEMES[BB.worldIndex(g.level)];this.$('#bombStat').textContent=`💣 ${g.maxBombs}`;this.$('#fireStat').textContent=`🔥 ${g.range}`;this.$('#speedStat').textContent=`⚡ Nv.${g.speedLevel}`;this.$('#enemyStat').textContent=g.exit?`🌀 ${g.exit.locked?'BLOQ.':'SAÍDA'}`:`👾 ${g.enemies.length}`;const gear=[g.kick?'👟':'',g.glove?'🧤':'',g.remote?'R':'',g.bombPass?'BP':'',g.wallPass?'WP':'',g.flamePass?'FP':''].filter(Boolean).join(' ');const temp=g.phase>0?`◇ ${Math.ceil(g.phase/1000)}s`:g.freeze>0?`⧖ ${Math.ceil(g.freeze/1000)}s`:g.nova>0?`✦x${g.nova}`:g.shield>0?`◉x${g.shield}`:g.pierce>0?`↠x${g.pierce}`:g.fast>0?`»x${g.fast}`:g.giant>0?`●x${g.giant}`:'SEM PODER';this.$('#powerStat').textContent=`${gear?gear+' · ':''}${temp}`;this.$('#remoteButton').disabled=!g.remote;this.$('#throwButton').disabled=!g.glove},
  overlay(top,title,score,primary){this.$('#overlay').hidden=false;this.$('#overlayTop').textContent=top;this.$('#overlayTitle').textContent=title;this.$('#overlayScore').textContent=score;this.$('#primary').textContent=primary;const paused=BB.game?.status==='paused';if(this.$('#overlayRestart'))this.$('#overlayRestart').hidden=!paused;if(this.$('#overlaySettings'))this.$('#overlaySettings').hidden=!paused},
  hideOverlay(){this.$('#overlay').hidden=true;const r=this.$('#resultStats');if(r){r.hidden=true;r.innerHTML=''}},
  showResults(data){const r=this.$('#resultStats');if(!r)return;r.hidden=false;r.innerHTML=`<span class="grade">${data.grade}</span><span>TEMPO<b>${data.remaining}s</b></span><span>INIMIGOS<b>${data.kills}</b></span><span>BLOCOS<b>${data.bricks}</b></span><span>POWER-UPS<b>${data.powers}</b></span><span>COMBO MÁX.<b>x${data.combo}</b></span><span>SEM DANO<b>${data.noDamage?'SIM':'NÃO'}</b></span><span>BÔNUS<b>+${data.bonus}</b></span>`},
  showMenu(tab=null){if(this.$('#resumePaused'))this.$('#resumePaused').hidden=true;this.$('#game').hidden=true;this.$('#story').hidden=true;this.$('#battle').hidden=true;this.$('#menu').hidden=false;BB.Battle?.stop();this.populateLevels();this.$('#record').textContent=BB.Save?.get('progress.record',0)||0;this.$('#bestLevel').textContent=BB.Save?.get('progress.bestLevel',1)||1;this.showMenuTab(tab||localStorage.getItem('bb-menu-tab')||'campaign');BB.Audio.stopMusic()},
  showMenuTab(tab='campaign'){document.querySelectorAll('[data-menu-tab]').forEach(b=>b.classList.toggle('active',b.dataset.menuTab===tab));document.querySelectorAll('[data-menu-panel]').forEach(p=>{const active=p.dataset.menuPanel===tab;p.hidden=!active;p.classList.toggle('active',active)});localStorage.setItem('bb-menu-tab',tab)},
  setDifficulty(v){BB.difficulty=v;BB.Save?.set('settings.difficulty',v);document.querySelectorAll('[data-diff]').forEach(b=>b.classList.toggle('selected',b.dataset.diff===v));const info=this.$('#difficultyInfo');if(info)info.textContent={easy:'IA básica: patrulha aleatória, reação lenta ao perigo, bombas raras, 5 vidas e mais tempo.',normal:'IA equilibrada: usa rotas, evita explosões próximas e persegue de forma razoável. 3 vidas.',hard:'IA avançada: pathfinding, previsão de reações em cadeia, busca rotas seguras, evita becos e usa bombas só com fuga. 2 vidas.'}[v]},
  setQuality(v){BB.quality=v;BB.Save?.set('settings.quality',v);document.body.dataset.quality=v;document.querySelectorAll('[data-quality]').forEach(b=>b.classList.toggle('selected',b.dataset.quality===v));const info=this.$('#qualityInfo');if(info)info.textContent={low:'Visual simplificado, 30 FPS alvo e menos partículas.',medium:'Equilíbrio entre efeitos e desempenho.',high:'Sprites, partículas, sombras e efeitos completos em alta fluidez.'}[v]},
  setMobileSize(v){document.body.dataset.mobile=v;BB.Save?.set('settings.mobile',v);document.querySelectorAll('[data-mobile]').forEach(b=>b.classList.toggle('selected',b.dataset.mobile===v))},
  setResolution(v){const modes={auto:{shell:'1040px',field:'960px',text:'Escala automática baseada na área disponível.'},1080:{shell:'1120px',field:'1080px',text:'Upscale para Full HD, mantendo o canvas lógico 650×550.'},720:{shell:'820px',field:'720px',text:'Escala para 720p/notebooks.'},480:{shell:'580px',field:'480px',text:'Escala compacta para telas pequenas ou modo leve.'}};const mode=modes[v]||modes.auto;document.body.dataset.resolution=v;document.documentElement.style.setProperty('--game-shell-width',mode.shell);document.documentElement.style.setProperty('--playfield-width',mode.field);BB.Save?.set('settings.resolution',v);document.querySelectorAll('[data-resolution]').forEach(b=>b.classList.toggle('selected',b.dataset.resolution===v));const info=this.$('#resolutionInfo');if(info)info.textContent=mode.text},
  keyLabel(k){return k===' '?'ESPAÇO':k==='Escape'?'ESC':k==='ArrowUp'?'↑':k==='ArrowDown'?'↓':k==='ArrowLeft'?'←':k==='ArrowRight'?'→':String(k).toUpperCase()},
  refreshBindings(){const controls=BB.Save?.get('controls',{})||{};document.querySelectorAll('[data-bind]').forEach(b=>{const k=controls[b.dataset.bind];const strong=b.querySelector('b');if(strong)strong.textContent=this.keyLabel(k)})},
  syncSettings(){const s=BB.Save?.data?.settings||{};this.setDifficulty(s.difficulty||'normal');this.setQuality(s.quality||'high');this.setMobileSize(s.mobile||'normal');this.setResolution(s.resolution||'auto');if(this.$('#battlePlayers'))this.$('#battlePlayers').value=String(s.battlePlayers||2);if(this.$('#battleArena'))this.$('#battleArena').value=String(s.battleArena||0);for(const [id,key] of [['masterVolume','masterVolume'],['musicVolume','musicVolume'],['sfxVolume','sfxVolume']]){const e=this.$(`#${id}`);if(e)e.value=Math.round((s[key]??.8)*100)}this.refreshBindings()}
};
