window.BB=window.BB||{};
BB.Battle={
  active:false,state:null,keys:new Set(),roundWins:[],ctx:null,count:2,padBombState:[],arenaIndex:0,suddenDeathStart:30000,suddenDeathStep:1150,
  ARENAS:[
    {name:'Jardim Neon',world:0,seed:1,density:.42},{name:'Circuito Fechado',world:0,seed:7,density:.55},
    {name:'Gelo Cósmico',world:1,seed:11,density:.46},{name:'Dunas Solares',world:2,seed:17,density:.50},
    {name:'Abismo Violeta',world:3,seed:23,density:.45},{name:'Arena Caótica',world:3,seed:31,density:.62}
  ],
  makeArena(index=0){const a=this.ARENAS[index%this.ARENAS.length],grid=Array.from({length:BB.ROWS},()=>Array(BB.COLS).fill(0));let seed=a.seed;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};for(let y=0;y<BB.ROWS;y++)for(let x=0;x<BB.COLS;x++){if(x===0||y===0||x===BB.COLS-1||y===BB.ROWS-1||(x%2===0&&y%2===0))grid[y][x]=1;else if(rnd()<a.density)grid[y][x]=2}const spawns=[{x:1,y:1},{x:11,y:9},{x:11,y:1},{x:1,y:9}];for(const p of spawns)for(const [dx,dy] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]]){const x=p.x+dx,y=p.y+dy;if(grid[y]?.[x]!==1)grid[y][x]=0}return{grid,arena:a}},
  start(count=2,arenaIndex=null){this.active=true;this.count=Number(count)===4?4:2;this.arenaIndex=arenaIndex==null?(BB.Save?.get('settings.battleArena',0)||0):Number(arenaIndex);this.roundWins=Array(this.count).fill(0);this.ctx=document.querySelector('#battleBoard').getContext('2d');this.ctx.imageSmoothingEnabled=false;this.newRound()},
  newRound(){const pack=this.makeArena(this.arenaIndex),spawns=[{x:1,y:1},{x:11,y:9},{x:11,y:1},{x:1,y:9}];this.state={grid:pack.grid,arena:pack.arena,players:spawns.slice(0,this.count).map((p,i)=>({...p,rx:p.x,ry:p.y,alive:true,move:0,id:`p${i+1}`,range:2,maxBombs:1,speed:125,kick:false,shield:0,score:0})),bombs:[],blasts:[],powers:[],timer:120000,over:0,winner:-1,suddenDeath:false,suddenTimer:0,suddenIndex:0,suddenPath:this.makeSuddenDeathPath()};this.padBombState=Array(this.count).fill(false);BB.Audio.musicFor(pack.arena.world*5+1,false)},
  stop(){this.active=false;this.keys.clear();BB.Audio.stopMusic()},press(k,on){if(on){const was=this.keys.has(k);this.keys.add(k);if(!was)for(let i=0;i<this.count;i++)if(this.inputFor(i).bomb===k)this.putBomb(i)}else this.keys.delete(k)},
  makeSuddenDeathPath(){const out=[];let left=1,right=BB.COLS-2,top=1,bottom=BB.ROWS-2;while(left<=right&&top<=bottom){for(let x=left;x<=right;x++)out.push({x,y:top});top++;for(let y=top;y<=bottom;y++)out.push({x:right,y});right--;if(top<=bottom){for(let x=right;x>=left;x--)out.push({x,y:bottom});bottom--}if(left<=right){for(let y=bottom;y>=top;y--)out.push({x:left,y});left++}}return out},
  suddenDeathStepOnce(){const s=this.state;if(!s?.suddenPath?.length||s.suddenIndex>=s.suddenPath.length)return;const p=s.suddenPath[s.suddenIndex++];s.grid[p.y][p.x]=1;s.bombs=s.bombs.filter(b=>!(b.x===p.x&&b.y===p.y));s.powers=s.powers.filter(q=>!(q.x===p.x&&q.y===p.y));for(const pl of s.players)if(pl.alive&&pl.x===p.x&&pl.y===p.y)pl.alive=false;BB.Audio.play('countdown',.28,1.18)},
  putBomb(pi){const s=this.state,p=s?.players[pi];if(!s||!p?.alive)return;const active=s.bombs.filter(b=>b.owner===pi).length;if(active>=p.maxBombs||s.bombs.some(b=>b.x===p.x&&b.y===p.y))return;s.bombs.push({x:p.x,y:p.y,owner:pi,timer:1900,range:p.range,id:BB.serial++,slide:null});BB.Audio.play('bomb_place')},
  walkable(x,y,allowBomb=false){const s=this.state,c=s?.grid[y]?.[x];return c===0&&(allowBomb||!s.bombs.some(b=>b.x===x&&b.y===y))},
  tryKick(p,nx,ny,dx,dy){if(!p.kick)return false;const b=this.state.bombs.find(b=>b.x===nx&&b.y===ny);if(!b)return false;const tx=nx+dx,ty=ny+dy;if(!this.walkable(tx,ty))return false;b.slide={dx,dy,t:0};BB.Audio.play('kick');return true},
  blastRay(b){const s=this.state,out=[{x:b.x,y:b.y,core:true,dx:0,dy:0}];for(const [dx,dy] of Object.values(BB.DIRS))for(let n=1;n<=b.range;n++){const x=b.x+dx*n,y=b.y+dy*n,c=s.grid[y]?.[x];if(c==null||c===1)break;out.push({x,y,dx,dy,end:n===b.range||c===2});if(c===2)break}return out},
  dropPower(x,y){if(Math.random()>.42)return;const kinds=['range','bomb','speed','kick','shield'];const kind=kinds[Math.floor(Math.random()*kinds.length)];this.state.powers.push({x,y,kind,phase:Math.random()*6})},
  collect(p){const s=this.state,i=s.powers.findIndex(q=>q.x===p.x&&q.y===p.y);if(i<0)return;const q=s.powers.splice(i,1)[0];if(q.kind==='range')p.range=Math.min(8,p.range+1);if(q.kind==='bomb')p.maxBombs=Math.min(6,p.maxBombs+1);if(q.kind==='speed')p.speed=Math.max(72,p.speed-12);if(q.kind==='kick')p.kick=true;if(q.kind==='shield')p.shield=Math.min(2,p.shield+1);p.score+=100;BB.Audio.play('powerup')},
  explode(){const s=this.state,queue=s.bombs.filter(b=>b.timer<=0);for(const b of queue){if(!s.bombs.includes(b))continue;const tiles=this.blastRay(b);s.bombs=s.bombs.filter(x=>x!==b);for(const t of tiles){const chained=s.bombs.find(x=>x.x===t.x&&x.y===t.y);if(chained)chained.timer=0;if(s.grid[t.y]?.[t.x]===2){s.grid[t.y][t.x]=0;this.dropPower(t.x,t.y)}}s.blasts.push(...tiles.map(t=>({...t,ttl:520,max:520})));for(const p of s.players)if(p.alive&&tiles.some(t=>t.x===p.x&&t.y===p.y)){if(p.shield>0){p.shield--;BB.Audio.play('hurt',.35)}else p.alive=false}BB.Audio.play('explosion')}},
  inputFor(pi){const defaults=[{up:'w',down:'s',left:'a',right:'d',bomb:' '},{up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',bomb:'Enter'},{up:'i',down:'k',left:'j',right:'l',bomb:'o'},{up:'8',down:'5',left:'4',right:'6',bomb:'0'}];return defaults[pi]},
  movePlayer(p,d){const [dx,dy]=BB.DIRS[d],nx=p.x+dx,ny=p.y+dy;if(!this.walkable(nx,ny)){if(!this.tryKick(p,nx,ny,dx,dy))return false}if(this.walkable(nx,ny)){p.x=nx;p.y=ny;p.move=p.speed;this.collect(p);return true}return false},
  pollGamepads(){if(!navigator.getGamepads)return;const pads=[...navigator.getGamepads()].filter(Boolean);pads.slice(0,this.count).forEach((pad,pi)=>{const p=this.state.players[pi];if(!p?.alive)return;const ax=pad.axes?.[0]||0,ay=pad.axes?.[1]||0;let dir=null;const up=!!pad.buttons?.[12]?.pressed,down=!!pad.buttons?.[13]?.pressed,left=!!pad.buttons?.[14]?.pressed,right=!!pad.buttons?.[15]?.pressed;if(up||down||left||right)dir=up?'up':down?'down':left?'left':'right';else if(Math.abs(ax)>.45||Math.abs(ay)>.45)dir=Math.abs(ax)>Math.abs(ay)?(ax<0?'left':'right'):(ay<0?'up':'down');if(dir&&p.move<=0)this.movePlayer(p,dir);const pressed=!!pad.buttons?.[0]?.pressed;if(pressed&&!this.padBombState[pi])this.putBomb(pi);this.padBombState[pi]=pressed})},
  update(dt){if(!this.active||!this.state)return;const s=this.state;if(s.over>0){s.over-=dt;if(s.over<=0){if(this.roundWins.some(w=>w>=3)){const winner=this.roundWins.findIndex(w=>w>=3);this.stop();document.querySelector('#battleOverlay').hidden=false;document.querySelector('#battleOverlayTitle').textContent=`JOGADOR ${winner+1} VENCEU!`;document.querySelector('#battleOverlayScore').textContent=this.roundWins.map((v,i)=>`P${i+1}: ${v}`).join(' · ')}else this.newRound()}return}s.timer-=dt;if(s.timer<=this.suddenDeathStart&&!s.suddenDeath){s.suddenDeath=true;s.suddenTimer=0;BB.Audio.play('countdown',.55,.85)}if(s.suddenDeath){s.suddenTimer-=dt;while(s.suddenTimer<=0&&s.suddenIndex<s.suddenPath.length){this.suddenDeathStepOnce();s.suddenTimer+=this.suddenDeathStep}}for(const p of s.players){p.rx=BB.lerp(p.rx,p.x,Math.min(1,dt*.02));p.ry=BB.lerp(p.ry,p.y,Math.min(1,dt*.02));p.move=Math.max(0,p.move-dt)}s.players.forEach((p,pi)=>{if(!p.alive||p.move>0)return;const m=this.inputFor(pi);for(const d of ['up','down','left','right'])if(this.keys.has(m[d])||this.keys.has(m[d].toUpperCase?.())){this.movePlayer(p,d);break}});this.pollGamepads();for(const b of s.bombs){b.timer-=dt;if(b.slide){b.slide.t+=dt;if(b.slide.t>=85){b.slide.t=0;const nx=b.x+b.slide.dx,ny=b.y+b.slide.dy;if(this.walkable(nx,ny)){b.x=nx;b.y=ny}else b.slide=null}}}s.blasts.forEach(b=>b.ttl-=dt);s.blasts=s.blasts.filter(b=>b.ttl>0);s.powers.forEach(p=>p.phase+=dt*.006);this.explode();const alive=s.players.filter(p=>p.alive);if(alive.length<=1||s.timer<=0){const winner=alive.length===1?s.players.indexOf(alive[0]):-1;if(winner>=0)this.roundWins[winner]++;s.winner=winner;s.over=1500}},
  draw(){if(!this.active||!this.state||!this.ctx)return;const c=this.ctx,s=this.state,w=s.arena.world,pal=BB.PALETTES[w];BB.Render.ensureWorld(w);c.clearRect(0,0,650,550);for(let y=0;y<BB.ROWS;y++)for(let x=0;x<BB.COLS;x++){const cell=s.grid[y][x],px=x*50,py=y*50,im=BB.Render.images[cell===0?`floor_${w+1}_${(x*3+y*5)%3}`:cell===1?`wall_${w+1}`:`brick_${w+1}`];if(im?.complete)c.drawImage(im,px,py,50,50);else{c.fillStyle=cell===0?pal.floor[0]:cell===1?pal.wall[0]:pal.brick[0];c.fillRect(px,py,50,50)}}for(const p of s.powers){const im=BB.Render.images[`power_${p.kind}`];if(im?.complete)c.drawImage(im,p.x*50+7,p.y*50+7,36,36)}for(const b of s.bombs){const im=BB.Render.images[`bomb_${Math.min(3,Math.floor((1-Math.min(1,b.timer/1900))*4))}`];if(im?.complete)c.drawImage(im,b.x*50+2,b.y*50+2,46,46)}for(const f of s.blasts){let n=f.core?'center':f.dx?'h':'v';if(f.end)n=f.dx?'end_h':'end_v';const im=BB.Render.images[`blast_${n}`]||BB.Render.images.blast_center;if(im?.complete){c.save();c.globalAlpha=Math.min(1,f.ttl/f.max*2);c.translate(f.x*50+25,f.y*50+25);if(f.end&&(f.dx<0||f.dy<0))c.rotate(Math.PI);c.drawImage(im,-30,-30,60,60);c.restore()}}s.players.forEach((p,i)=>{if(!p.alive)return;const im=BB.Render.images[`battle_player_${i+1}`]||BB.Render.playerFrames.walk.down[0];if(im?.complete)c.drawImage(im,p.rx*50-7,p.ry*50-7,64,64);if(p.shield){c.strokeStyle='#8cecff';c.beginPath();c.arc(p.rx*50+25,p.ry*50+25,22,0,Math.PI*2);c.stroke()}});c.fillStyle='#07101ddd';c.fillRect(105,8,440,30);c.fillStyle='#fff';c.font='bold 11px monospace';c.textAlign='center';c.fillText(`${s.arena.name} · ${this.roundWins.map((v,i)=>`P${i+1} ${v}`).join('  ·  ')} · ${Math.max(0,Math.ceil(s.timer/1000))}s`,325,28);if(s.suddenDeath){c.save();c.fillStyle=`rgba(255,55,90,${.72+.2*Math.sin(performance.now()*.012)})`;c.fillRect(180,44,290,26);c.fillStyle='#fff';c.font='bold 13px monospace';c.fillText('⚠ SUDDEN DEATH · ARENA FECHANDO ⚠',325,62);c.restore()}if(s.over>0){c.fillStyle='#040913cc';c.fillRect(0,0,650,550);c.fillStyle='#fff';c.font='36px Impact,sans-serif';c.fillText(s.winner<0?'EMPATE!':`JOGADOR ${s.winner+1} VENCEU!`,325,280)}}
};
