window.BB=window.BB||{};
BB.Battle={
  active:false,state:null,keys:new Set(),roundWins:[],ctx:null,count:2,padBombState:[],
  start(count=2){this.active=true;this.count=Number(count)===4?4:2;this.roundWins=Array(this.count).fill(0);this.ctx=document.querySelector('#battleBoard').getContext('2d');this.ctx.imageSmoothingEnabled=false;this.newRound()},
  newRound(){const grid=BB.makeGrid(1),spawns=[{x:1,y:1},{x:11,y:9},{x:11,y:1},{x:1,y:9}];for(const p of spawns.slice(0,this.count))for(const [dx,dy] of [[0,0],[1,0],[-1,0],[0,1],[0,-1]]){const x=p.x+dx,y=p.y+dy;if(grid[y]?.[x]!==1)grid[y][x]=0}this.state={grid,players:spawns.slice(0,this.count).map((p,i)=>({...p,rx:p.x,ry:p.y,alive:true,move:0,id:`p${i+1}`,range:2,maxBombs:1})),bombs:[],blasts:[],timer:120000,over:0,winner:-1};this.padBombState=Array(this.count).fill(false)},
  stop(){this.active=false;this.keys.clear()},press(k,on){if(on)this.keys.add(k);else this.keys.delete(k)},
  putBomb(pi){const s=this.state,p=s?.players[pi];if(!s||!p?.alive)return;const active=s.bombs.filter(b=>b.owner===pi).length;if(active>=p.maxBombs||s.bombs.some(b=>b.x===p.x&&b.y===p.y))return;s.bombs.push({x:p.x,y:p.y,owner:pi,timer:1900,range:p.range,id:BB.serial++});BB.Audio.play('bomb_place')},
  walkable(x,y){const s=this.state,c=s?.grid[y]?.[x];return c===0&&!s.bombs.some(b=>b.x===x&&b.y===y)},
  blastRay(b){const s=this.state,out=[{x:b.x,y:b.y}];for(const [dx,dy] of Object.values(BB.DIRS))for(let n=1;n<=b.range;n++){const x=b.x+dx*n,y=b.y+dy*n,c=s.grid[y]?.[x];if(c==null||c===1)break;out.push({x,y});if(c===2)break}return out},
  explode(){const s=this.state;for(const b of [...s.bombs])if(b.timer<=0){const tiles=this.blastRay(b);s.bombs=s.bombs.filter(x=>x!==b);for(const t of tiles)if(s.grid[t.y]?.[t.x]===2)s.grid[t.y][t.x]=0;s.blasts.push(...tiles.map(t=>({...t,ttl:500})));for(const p of s.players)if(p.alive&&tiles.some(t=>t.x===p.x&&t.y===p.y))p.alive=false;BB.Audio.play('explosion')}},
  inputFor(pi){const maps=[{up:'w',down:'s',left:'a',right:'d',bomb:' '},{up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',bomb:'Enter'},{up:'i',down:'k',left:'j',right:'l',bomb:'o'},{up:'8',down:'5',left:'4',right:'6',bomb:'0'}];return maps[pi]},
  pollGamepads(){if(!navigator.getGamepads)return;const pads=[...navigator.getGamepads()].filter(Boolean);pads.slice(0,this.count).forEach((pad,pi)=>{const p=this.state.players[pi];if(!p?.alive)return;const ax=pad.axes?.[0]||0,ay=pad.axes?.[1]||0;let dir=null;if(Math.abs(ax)>.45||Math.abs(ay)>.45)dir=Math.abs(ax)>Math.abs(ay)?(ax<0?'left':'right'):(ay<0?'up':'down');if(dir&&p.move<=0){const [dx,dy]=BB.DIRS[dir],x=p.x+dx,y=p.y+dy;if(this.walkable(x,y)){p.x=x;p.y=y;p.move=125}}const pressed=!!pad.buttons?.[0]?.pressed;if(pressed&&!this.padBombState[pi])this.putBomb(pi);this.padBombState[pi]=pressed})},
  update(dt){if(!this.active||!this.state)return;const s=this.state;if(s.over>0){s.over-=dt;if(s.over<=0){if(this.roundWins.some(w=>w>=3)){const winner=this.roundWins.findIndex(w=>w>=3);this.stop();document.querySelector('#battleOverlay').hidden=false;document.querySelector('#battleOverlayTitle').textContent=`JOGADOR ${winner+1} VENCEU!`;document.querySelector('#battleOverlayScore').textContent=this.roundWins.map((v,i)=>`P${i+1}: ${v}`).join(' · ')}else this.newRound()}return}s.timer-=dt;for(const p of s.players){p.rx=BB.lerp(p.rx,p.x,Math.min(1,dt*.02));p.ry=BB.lerp(p.ry,p.y,Math.min(1,dt*.02));p.move=Math.max(0,p.move-dt)}s.players.forEach((p,pi)=>{if(!p.alive||p.move>0)return;const m=this.inputFor(pi);for(const d of ['up','down','left','right'])if(this.keys.has(m[d])||this.keys.has(m[d].toUpperCase?.())){const [dx,dy]=BB.DIRS[d],x=p.x+dx,y=p.y+dy;if(this.walkable(x,y)){p.x=x;p.y=y;p.move=125}break}});this.pollGamepads();s.bombs.forEach(b=>b.timer-=dt);s.blasts.forEach(b=>b.ttl-=dt);s.blasts=s.blasts.filter(b=>b.ttl>0);this.explode();const alive=s.players.filter(p=>p.alive);if(alive.length<=1||s.timer<=0){const winner=alive.length===1?s.players.indexOf(alive[0]):-1;if(winner>=0)this.roundWins[winner]++;s.winner=winner;s.over=1400}},
  draw(){if(!this.active||!this.state||!this.ctx)return;const c=this.ctx,s=this.state,pal=BB.PALETTES[0];c.clearRect(0,0,650,550);for(let y=0;y<BB.ROWS;y++)for(let x=0;x<BB.COLS;x++){const cell=s.grid[y][x],px=x*50,py=y*50;if(cell===0){const g=c.createLinearGradient(px,py,px+50,py+50);g.addColorStop(0,pal.floor[0]);g.addColorStop(1,pal.floor[1]);c.fillStyle=g;c.fillRect(px,py,50,50)}else{const im=BB.Render.images[cell===1?'wall_1':'brick_1'];if(im?.complete)c.drawImage(im,px,py,50,50);else{c.fillStyle=cell===1?pal.wall[0]:pal.brick[0];c.fillRect(px+2,py+2,46,46)}}}for(const b of s.bombs){const im=BB.Render.images[`bomb_${Math.min(3,Math.floor((1-Math.min(1,b.timer/1900))*4))}`];if(im?.complete)c.drawImage(im,b.x*50+2,b.y*50+2,46,46)}for(const f of s.blasts){const im=BB.Render.images.blast_center;if(im?.complete){c.globalAlpha=Math.min(1,f.ttl/250);c.drawImage(im,f.x*50-5,f.y*50-5,60,60);c.globalAlpha=1}}const filters=['none','hue-rotate(170deg) saturate(1.5)','hue-rotate(75deg) saturate(1.5)','hue-rotate(275deg) saturate(1.5)'];s.players.forEach((p,i)=>{if(!p.alive)return;const im=BB.Render.playerFrames.walk.down[0];c.save();c.filter=filters[i]||'none';if(im?.complete)c.drawImage(im,p.rx*50,p.ry*50,50,50);c.restore()});c.fillStyle='#07101ddd';c.fillRect(135,8,380,28);c.fillStyle='#fff';c.font='bold 11px monospace';c.textAlign='center';c.fillText(`${this.roundWins.map((v,i)=>`P${i+1} ${v}`).join('  ·  ')}  ·  ${Math.ceil(s.timer/1000)}s`,325,27);if(s.over>0){c.fillStyle='#040913cc';c.fillRect(0,0,650,550);c.fillStyle='#fff';c.font='36px Impact,sans-serif';c.fillText(s.winner<0?'EMPATE!':`JOGADOR ${s.winner+1} VENCEU A RODADA!`,325,280)}}
};
