window.BB=window.BB||{};
Object.assign(BB,{serial:1,game:null,difficulty:'normal',particles:[],texts:[],shake:0,flash:0});

BB.makePlayer=function(){return{x:1,y:1,rx:1,ry:1,facing:'down',frame:0,action:'idle',actionTimer:0,actionDuration:0,actionFrame:0}};
BB.setPlayerAction=function(action,duration=0){const p=BB.game?.player;if(!p)return;p.action=action;p.actionTimer=duration;p.actionDuration=duration;p.actionFrame=0};
BB.clearPlayerAction=function(){const p=BB.game?.player;if(!p)return;p.action='idle';p.actionTimer=0;p.actionDuration=0;p.actionFrame=0};
BB.isPlayerBusy=function(){const g=BB.game;return !!(g?.pendingRespawn>0||g?.pendingGameOver>0||['place','hurt','dead'].includes(g?.player?.action))};
BB.resetPlayerToStart=function(){if(BB.game)BB.game.player=BB.makePlayer()};

BB.pickHiddenContent=function(grid,level,def){
  const bricks=[];for(let y=1;y<BB.ROWS-1;y++)for(let x=1;x<BB.COLS-1;x++)if(grid[y][x]===2)bricks.push({x,y});
  bricks.sort((a,b)=>(b.x+b.y)-(a.x+a.y));
  const exitSpot=bricks[0]||{x:BB.COLS-2,y:BB.ROWS-2};
  const hidden={};
  const powerKinds=['range','bomb','speed','kick','glove','shield','chrono','remote','pierce','bombpass','wallpass','flamepass'];
  let cursor=1;
  const itemCount=Math.min(5,2+Math.floor(level/5));
  for(let i=0;i<itemCount&&cursor<bricks.length;i++,cursor++)hidden[BB.key(bricks[cursor])]={type:'power',kind:powerKinds[(level+i*3)%powerKinds.length]};
  if(def.objective==='keys')for(let i=0;i<def.target&&cursor<bricks.length;i++,cursor++)hidden[BB.key(bricks[cursor])]={type:'key'};
  return{exitSpot,hidden};
};

BB.makeGame=function(level=1,carry={}){
  const grid=BB.makeGrid(level),cfg=BB.CONFIG[BB.difficulty],def=BB.levelDef(level),hiddenInfo=BB.pickHiddenContent(grid,level,def);
  const base={lives:carry.lives??cfg.lives,score:carry.score??0,range:carry.range??Math.min(6,2+Math.floor((level-1)/4)),maxBombs:carry.maxBombs??Math.min(4,1+Math.floor((level-1)/6)),speedLevel:carry.speedLevel??Math.min(5,1+Math.floor((level-1)/5)),shield:carry.shield??0,nova:carry.nova??0,remote:carry.remote??false,pierce:carry.pierce??0,fast:carry.fast??0,giant:carry.giant??0,kick:carry.kick??false,glove:carry.glove??false,bombPass:carry.bombPass??false,wallPass:carry.wallPass??false,flamePass:carry.flamePass??false};
  const enemies=BB.spawnEnemies(grid,level,BB.difficulty);
  return{grid,level,def,enemies,bombs:[],blasts:[],powers:[],hazards:[],breakingBricks:[],deadEnemies:[],exit:null,exitSpot:hiddenInfo.exitSpot,exitRevealed:false,hidden:hiddenInfo.hidden,player:BB.makePlayer(),...base,continues:carry.continues??2,time:cfg.time*1000,initialTime:cfg.time*1000,moveDelay:Math.max(72,150-(base.speedLevel-1)*12),moveTimer:0,inv:0,freeze:0,phase:0,status:'playing',combo:0,comboTimer:0,lastReward:'',entry:{...base},pendingRespawn:0,pendingGameOver:0,objectiveProgress:0,objectiveComplete:false,surviveElapsed:0,introTimer:(level%5===0||[4,9,14,19].includes(level))?1600:0,stats:{kills:0,bricks:0,powers:0,maxCombo:0,bombs:0,damage:0},countdownMark:31,portalPenalty:false};
};

BB.walkable=function(x,y,enemyKind='',actor='player'){
  const g=BB.game;if(!g)return false;const cell=g.grid[y]?.[x];if(cell==null||cell===1)return false;
  const ghost=enemyKind==='ghost',player=actor==='player';
  if(cell===2&&!ghost&&!(player&&(g.phase>0||g.wallPass)))return false;
  if(g.bombs.some(b=>b.x===x&&b.y===y)&&!(player&&g.bombPass))return false;
  if(enemyKind&&g.enemies.some(e=>e.x===x&&e.y===y&&!e.deadTimer))return false;
  return true;
};

BB.addText=(x,y,text,color='#fff')=>BB.texts.push({x:x*BB.TILE+25,y:y*BB.TILE+18,text,color,life:900});
BB.burst=function(x,y,color,count=10,speed=110){const q=BB.quality==='low'?0:BB.quality==='medium'?.45:1;for(let i=0;i<Math.round(count*q);i++){const a=Math.random()*Math.PI*2,v=(.35+Math.random()*.65)*speed;BB.particles.push({x:x*BB.TILE+25,y:y*BB.TILE+25,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:350+Math.random()*400,max:750,size:2+Math.random()*4,color,gravity:15+Math.random()*50})}};

BB.putBomb=function(owner='player',x,y){const g=BB.game;if(!g||g.status!=='playing'||g.introTimer>0)return;if(owner==='player'){x=g.player.x;y=g.player.y;const active=g.bombs.filter(b=>b.owner==='player').length;if(active>=g.maxBombs||g.bombs.some(b=>b.x===x&&b.y===y))return;}else if(g.bombs.some(b=>b.x===x&&b.y===y))return;const remote=owner==='player'&&g.remote,fast=owner==='player'&&g.fast>0,giant=owner==='player'&&g.giant>0,pierce=owner==='player'&&g.pierce>0;if(fast)g.fast--;if(giant)g.giant--;if(pierce)g.pierce--;g.bombs.push({x,y,rx:x,ry:y,id:BB.serial++,owner,timer:remote?999999:(fast?1150:2100),range:(owner==='enemy'?2:g.range)+(giant?2:0),nova:owner==='player'&&g.nova>0,pierce,giant,remote,pulse:0,slide:null,throw:null});if(owner==='player'){g.stats.bombs++;BB.setPlayerAction('place',220)}if(owner==='player'&&g.nova>0)g.nova--;BB.Audio.play('bomb_place')};
BB.remoteDetonate=function(){const b=BB.game?.bombs.find(b=>b.owner==='player'&&b.remote);if(b){b.timer=0;BB.addText(b.x,b.y,'DETONE!','#ffcf61')}};
BB.throwBomb=function(){const g=BB.game;if(!g?.glove)return;const [dx,dy]=BB.DIRS[g.player.facing],b=g.bombs.find(b=>b.x===g.player.x+dx&&b.y===g.player.y+dy);if(!b)return;let tx=b.x,ty=b.y;for(let i=0;i<3;i++){const nx=tx+dx,ny=ty+dy;if(!BB.walkable(nx,ny,'','player'))break;tx=nx;ty=ny}if(tx===b.x&&ty===b.y)return;b.throw={sx:b.x,sy:b.y,tx,ty,t:0,duration:380};b.x=tx;b.y=ty;BB.Audio.play('throw');BB.addText(tx,ty,'ARREMESSO!','#8cecff')};
BB.tryKick=function(nx,ny,dx,dy){const g=BB.game,b=g.bombs.find(b=>b.x===nx&&b.y===ny);if(!b||!g.kick)return false;const bx=nx+dx,by=ny+dy;if(!BB.walkable(bx,by,'','player'))return false;b.slide={dx,dy,step:0};BB.Audio.play('kick');return true};

BB.damagePlayer=function(cause='contact'){const g=BB.game;if(!g||g.inv>0||g.status!=='playing'||g.pendingRespawn>0||g.pendingGameOver>0)return;if(cause==='blast'&&g.flamePass){g.inv=250;return}if(g.shield>0){g.shield--;g.inv=1100;BB.addText(g.player.x,g.player.y,'ESCUDO!','#62f5ff');BB.Audio.play('powerup');return}g.lives--;g.stats.damage++;g.inv=1800;g.combo=0;BB.shake=12;BB.flash=150;BB.Audio.play('hurt');navigator.vibrate?.([70,30,70]);if(g.lives<=0){g.lives=0;BB.setPlayerAction('dead',900);g.pendingGameOver=900;BB.addText(g.player.x,g.player.y,'DERROTADO','#ff5578');return}BB.setPlayerAction('hurt',700);g.pendingRespawn=700;BB.addText(g.player.x,g.player.y,'-1 VIDA','#ff5578')};

BB.blastRay=function(b){const g=BB.game,out=[{x:b.x,y:b.y,core:true,dx:0,dy:0,end:false}],dirs=Object.values(BB.DIRS).slice();if(b.nova)dirs.push([1,1],[1,-1],[-1,1],[-1,-1]);for(const [dx,dy] of dirs){for(let n=1;n<=b.range;n++){const x=b.x+dx*n,y=b.y+dy*n,cell=g.grid[y]?.[x];if(cell==null||cell===1)break;const brick=cell===2;out.push({x,y,core:false,dx,dy,brick,end:n===b.range||(brick&&!b.pierce)});if(brick&&!b.pierce)break}}return out};
BB.dangerSet=function(){const g=BB.game,set=new Set(g.blasts.map(BB.key));for(const b of g.bombs){if(b.timer>850)continue;for(const t of BB.blastRay(b))set.add(BB.key(t))}for(const h of g.hazards)set.add(BB.key(h));return set};

BB.killEnemy=function(e){const g=BB.game,constDead=e.boss?980:520;e.deadTimer=constDead;g.deadEnemies.push({...e,deadTimer:constDead});g.enemies=g.enemies.filter(x=>x!==e);g.stats.kills++;BB.Audio.play('enemy_die');BB.burst(e.x,e.y,e.boss?'#ffc849':'#ff5277',e.boss?36:12,e.boss?180:150);if(e.boss){BB.shake=Math.max(BB.shake,18);BB.flash=200;BB.addText(e.x,e.y,'BOSS DERROTADO!','#ffe270')}};
BB.damageEnemy=function(enemy,amount,sourceId){enemy.hitSources=enemy.hitSources||{};if(enemy.hitSources[sourceId])return false;enemy.hitSources[sourceId]=1;enemy.hp-=amount;enemy.hit=550;BB.Audio.play(enemy.boss?'boss_hit':'explosion',enemy.boss?.5:.32);BB.addText(enemy.x,enemy.y,enemy.hp>0?'-1':'KO!',enemy.boss?'#ffe267':'#ff8aa0');if(enemy.boss){const ratio=enemy.hp/enemy.maxHp;enemy.phase=ratio<=.34?3:ratio<=.67?2:1}return enemy.hp<=0};

BB.revealBrickContent=function(x,y){const g=BB.game,k=`${x},${y}`;if(x===g.exitSpot.x&&y===g.exitSpot.y){g.exitRevealed=true;g.exit={x,y,phase:0,locked:!g.objectiveComplete};BB.Audio.play('portal');BB.addText(x,y,'PORTAL!','#52f4c9')}const h=g.hidden[k];if(h){delete g.hidden[k];if(h.type==='key'){g.powers.push({x,y,id:BB.serial++,kind:'key',phase:0});}else g.powers.push({x,y,id:BB.serial++,kind:h.kind,phase:0})}};
BB.portalHitPenalty=function(){const g=BB.game;if(!g.exit||g.portalPenalty)return;g.portalPenalty=true;g.objectiveComplete=false;g.exit.locked=true;BB.Audio.play('portal_hit');BB.addText(g.exit.x,g.exit.y,'PORTAL INSTÁVEL!','#ff5578');const spots=[];for(let y=1;y<BB.ROWS-1;y++)for(let x=1;x<BB.COLS-1;x++)if(g.grid[y][x]===0&&Math.abs(x-g.player.x)+Math.abs(y-g.player.y)>5)spots.push({x,y});for(let i=0;i<Math.min(3,spots.length);i++){const p=spots[(i*7+g.level)%spots.length];g.enemies.push({...p,rx:p.x,ry:p.y,id:BB.serial++,kind:'hunter',hp:1,maxHp:1,boss:false,timer:500,special:0,hit:0,phase:1,frame:0,facing:'left',hitSources:{}})}};

BB.explodeDue=function(){const g=BB.game,queue=g.bombs.filter(b=>b.timer<=0).map(b=>b.id);if(!queue.length)return;const exploded=new Set(),all=[],destroyed=new Set();while(queue.length){const id=queue.shift();if(exploded.has(id))continue;const b=g.bombs.find(x=>x.id===id);if(!b)continue;exploded.add(id);const tiles=BB.blastRay(b);all.push({id,b,tiles});for(const t of tiles)for(const other of g.bombs)if(!exploded.has(other.id)&&BB.same(t,other))queue.push(other.id)}g.bombs=g.bombs.filter(b=>!exploded.has(b.id));let kills=0;for(const pack of all){const hostile=pack.b.owner==='enemy',fire=new Set(pack.tiles.map(BB.key));for(const t of pack.tiles)if(t.brick&&!destroyed.has(BB.key(t))){destroyed.add(BB.key(t));g.grid[t.y][t.x]=0;g.stats.bricks++;g.score+=10;g.breakingBricks.push({x:t.x,y:t.y,ttl:360,max:360});BB.Audio.play('brick_break',.28);BB.revealBrickContent(t.x,t.y)}if(g.exit&&fire.has(BB.key(g.exit)))BB.portalHitPenalty();if(!hostile){for(const e of [...g.enemies])if(fire.has(BB.key(e))){const dead=BB.damageEnemy(e,1,pack.id);if(dead){kills++;BB.killEnemy(e)}}}if(fire.has(BB.key(g.player)))BB.damagePlayer('blast');g.blasts.push(...pack.tiles.map(t=>({...t,ttl:650,max:650,hostile,sourceId:pack.id})))}if(kills){g.combo++;g.comboTimer=1800;g.stats.maxCombo=Math.max(g.stats.maxCombo,g.combo);g.score+=kills*150*g.combo;BB.addText(g.player.x,g.player.y,g.combo>1?`COMBO x${g.combo}`:`+${kills*150}`,'#fff06a')}BB.shake=Math.min(18,BB.shake+exploded.size*4);BB.flash=80;BB.Audio.play('explosion');navigator.vibrate?.(45)};

BB.POWER_KINDS=['range','bomb','speed','life','kick','glove','remote','pierce','fast','giant','shield','chrono','nova','phase','bombpass','wallpass','flamepass'];
BB.dropPower=function(){/* power-ups are pre-hidden per arena in v0.5.0 */};
BB.collectPower=function(){const g=BB.game,p=g.powers.find(p=>BB.same(p,g.player));if(!p)return;g.powers=g.powers.filter(x=>x.id!==p.id);g.stats.powers++;g.score+=100;if(p.kind==='key'){g.objectiveProgress++;BB.addText(p.x,p.y,'NÚCLEO!','#ffe270');BB.Audio.play('powerup');return}const labels={range:'ALCANCE +1',bomb:'BOMBA +1',speed:'VELOCIDADE +1',life:'VIDA +1',kick:'CHUTE',glove:'ARREMESSO',remote:'CONTROLE REMOTO',pierce:'PERFURANTE x3',fast:'BOMBA RÁPIDA x3',giant:'BOMBA GIGANTE x2',shield:'ESCUDO',chrono:'TEMPO +20s',nova:'NOVA x2',phase:'FANTASMA 10s',bombpass:'PASSA BOMBAS',wallpass:'PASSA PAREDES',flamepass:'IMUNE AO FOGO'};if(p.kind==='range')g.range=BB.clamp(g.range+1,2,9);if(p.kind==='bomb')g.maxBombs=BB.clamp(g.maxBombs+1,1,7);if(p.kind==='speed'){g.speedLevel=BB.clamp(g.speedLevel+1,1,7);g.moveDelay=Math.max(72,150-(g.speedLevel-1)*12)}if(p.kind==='life'){g.lives=BB.clamp(g.lives+1,1,7);BB.Audio.play('life')}if(p.kind==='kick')g.kick=true;if(p.kind==='glove')g.glove=true;if(p.kind==='remote')g.remote=true;if(p.kind==='pierce')g.pierce+=3;if(p.kind==='fast')g.fast+=3;if(p.kind==='giant')g.giant+=2;if(p.kind==='shield')g.shield=BB.clamp(g.shield+1,0,3);if(p.kind==='chrono'){g.time+=20000;g.freeze=Math.max(g.freeze,4000)}if(p.kind==='nova')g.nova+=2;if(p.kind==='phase')g.phase=Math.max(g.phase,10000);if(p.kind==='bombpass')g.bombPass=true;if(p.kind==='wallpass')g.wallPass=true;if(p.kind==='flamepass')g.flamePass=true;BB.addText(p.x,p.y,labels[p.kind]||p.kind,'#52f4c9');BB.Audio.play('powerup')};

BB.objectiveSatisfied=function(){const g=BB.game,d=g.def;if(g.portalPenalty&&g.enemies.length>0)return false;if(d.objective==='clear')return g.enemies.length===0;if(d.objective==='bricks')return g.stats.bricks>=d.target;if(d.objective==='keys')return g.objectiveProgress>=d.target;if(d.objective==='survive')return g.surviveElapsed>=d.target*1000;if(d.objective==='miniboss'||d.objective==='boss')return !g.enemies.some(e=>e.boss);return g.enemies.length===0};
BB.updateObjective=function(dt){const g=BB.game;if(g.def.objective==='survive'&&!g.objectiveComplete)g.surviveElapsed+=dt;if(!g.objectiveComplete&&BB.objectiveSatisfied()){g.objectiveComplete=true;g.score+=500;BB.addText(g.player.x,g.player.y,'OBJETIVO COMPLETO!','#ffe270');if(g.exit)g.exit.locked=false;BB.Audio.play('portal')}};
BB.spawnExit=function(){const g=BB.game;if(g.exitRevealed&&!g.exit)g.exit={x:g.exitSpot.x,y:g.exitSpot.y,phase:0,locked:!g.objectiveComplete}};

BB.enemyMove=function(e){const g=BB.game,danger=BB.dangerSet();let opts=Object.entries(BB.DIRS).map(([name,[dx,dy]])=>({name,x:e.x+dx,y:e.y+dy,dx,dy})).filter(p=>BB.walkable(p.x,p.y,e.kind,'enemy'));if(!opts.length)return;const smart=['hunter','boss','bomber','ghost'].includes(e.kind);if(smart){const safe=opts.filter(p=>!danger.has(`${p.x},${p.y}`));if(safe.length)opts=safe}if(e.kind==='slime'&&Math.random()<.3){const p=opts[Math.floor(Math.random()*opts.length)],jx=e.x+p.dx*2,jy=e.y+p.dy*2;if(BB.walkable(jx,jy,e.kind,'enemy')&&!danger.has(`${jx},${jy}`)){e.x=jx;e.y=jy;return}}if(['hunter','boss','bomber'].includes(e.kind))opts.sort((a,b)=>(Math.abs(a.x-g.player.x)+Math.abs(a.y-g.player.y))-(Math.abs(b.x-g.player.x)+Math.abs(b.y-g.player.y)));const p=['hunter','boss','bomber'].includes(e.kind)?opts[0]:opts[Math.floor(Math.random()*opts.length)];e.x=p.x;e.y=p.y;e.facing=p.name};

BB.rayAttack=function(e,dx,dy,len,tiles){for(let n=1;n<=len;n++){const x=e.x+dx*n,y=e.y+dy*n,cell=BB.game.grid[y]?.[x];if(cell==null||cell===1||cell===2)break;if(!tiles.some(t=>t.x===x&&t.y===y))tiles.push({x,y})}};
BB.bossAttack=function(e){const g=BB.game,w=BB.worldIndex(g.level),tiles=[];e.attackTimer=780;e.attackDuration=780;e.attackStyle=['crystal','frost','sand','void'][w]||'boss';if(w===0){Object.values(BB.DIRS).forEach(([dx,dy])=>BB.rayAttack(e,dx,dy,1+e.phase,tiles));if(e.phase===3){const dx=Math.sign(g.player.x-e.x),dy=Math.sign(g.player.y-e.y);if(BB.walkable(e.x+dx,e.y+dy,e.kind,'enemy')){e.x+=dx;e.y+=dy}}}if(w===1){[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]].forEach(([dx,dy])=>BB.rayAttack(e,dx,dy,1+e.phase,tiles));if(e.phase>=2)for(let i=0;i<2;i++){const x=1+Math.floor(Math.random()*(BB.COLS-2)),y=1+Math.floor(Math.random()*(BB.ROWS-2));if(g.grid[y][x]===0)g.grid[y][x]=2}}if(w===2){const dx=Math.sign(g.player.x-e.x)||1,dy=Math.sign(g.player.y-e.y)||1;BB.rayAttack(e,dx,0,3+e.phase,tiles);BB.rayAttack(e,0,dy,3+e.phase,tiles);if(e.phase>=2){const spots=[];for(let y=1;y<BB.ROWS-1;y++)for(let x=1;x<BB.COLS-1;x++)if(g.grid[y][x]===0)spots.push({x,y});const p=spots[Math.floor(Math.random()*spots.length)];if(p){e.x=p.x;e.y=p.y;e.rx=p.x;e.ry=p.y}}}if(w===3){[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]].forEach(([dx,dy])=>BB.rayAttack(e,dx,dy,1+e.phase,tiles));if(e.phase>=2)for(let i=0;i<e.phase;i++){const p={x:1+Math.floor(Math.random()*(BB.COLS-2)),y:1+Math.floor(Math.random()*(BB.ROWS-2))};if(g.grid[p.y][p.x]===0)g.enemies.push({...p,rx:p.x,ry:p.y,id:BB.serial++,kind:'ghost',hp:1,maxHp:1,boss:false,timer:600,special:0,hit:0,phase:1,frame:0,facing:'left',hitSources:{},deadTimer:0,attackTimer:0,attackDuration:0,attackStyle:'idle'})}}g.hazards.push(...tiles.map(t=>({...t,ttl:850,max:850})));BB.shake=Math.max(BB.shake,10);BB.flash=120;BB.addText(e.x,e.y,`ATAQUE FASE ${e.phase}!`,'#ff5dd7')};

BB.updateBombMotion=function(dt){const g=BB.game;for(const b of g.bombs){if(b.throw){b.throw.t+=dt;const q=Math.min(1,b.throw.t/b.throw.duration);b.rx=BB.lerp(b.throw.sx,b.throw.tx,q);b.ry=BB.lerp(b.throw.sy,b.throw.ty,q)-Math.sin(q*Math.PI)*.8;if(q>=1){b.rx=b.x;b.ry=b.y;b.throw=null}continue}if(b.slide){b.slide.step+=dt;if(b.slide.step>=90){b.slide.step=0;const nx=b.x+b.slide.dx,ny=b.y+b.slide.dy;if(!BB.walkable(nx,ny,'','player')){b.slide=null}else{b.x=nx;b.y=ny;b.rx=nx;b.ry=ny}}}else{b.rx=b.x;b.ry=b.y}}};
BB.updateEffects=function(dt){BB.shake=Math.max(0,BB.shake-dt*.045);BB.flash=Math.max(0,BB.flash-dt);BB.particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt/1000;p.y+=p.vy*dt/1000;p.vy+=p.gravity*dt/1000});BB.particles=BB.particles.filter(p=>p.life>0);BB.texts.forEach(t=>{t.life-=dt;t.y-=dt*.025});BB.texts=BB.texts.filter(t=>t.life>0)};

BB.update=function(dt){BB.updateEffects(dt);const g=BB.game;if(!g||g.status!=='playing')return;if(g.introTimer>0){g.introTimer=Math.max(0,g.introTimer-dt);if(g.introTimer===0)BB.Audio.play('boss_intro');return}g.time=Math.max(0,g.time-dt);g.moveTimer=Math.max(0,g.moveTimer-dt);g.inv=Math.max(0,g.inv-dt);g.freeze=Math.max(0,g.freeze-dt);g.phase=Math.max(0,g.phase-dt);g.comboTimer=Math.max(0,g.comboTimer-dt);if(!g.comboTimer)g.combo=0;const seconds=Math.ceil(g.time/1000);if(seconds<=30&&seconds<g.countdownMark){g.countdownMark=seconds;if(seconds<=10||seconds%5===0)BB.Audio.play('countdown',.22);BB.Audio.setUrgency(true)}else if(seconds>30)BB.Audio.setUrgency(false);
if(g.pendingRespawn>0){g.pendingRespawn=Math.max(0,g.pendingRespawn-dt);if(g.pendingRespawn<=0)BB.resetPlayerToStart()}if(g.pendingGameOver>0){g.pendingGameOver=Math.max(0,g.pendingGameOver-dt);if(g.pendingGameOver<=0){BB.finish('gameover');return}}
g.player.rx=BB.lerp(g.player.rx,g.player.x,Math.min(1,dt*.018));g.player.ry=BB.lerp(g.player.ry,g.player.y,Math.min(1,dt*.018));g.player.frame+=dt*.014;if(g.player.actionTimer>0){g.player.actionTimer=Math.max(0,g.player.actionTimer-dt);g.player.actionFrame=g.player.actionDuration-g.player.actionTimer;if(g.player.actionTimer<=0&&['place','hurt'].includes(g.player.action)&&g.pendingRespawn<=0)BB.clearPlayerAction()}
g.bombs.forEach(b=>{b.timer-=dt;b.pulse+=dt*.014});BB.updateBombMotion(dt);g.blasts.forEach(b=>b.ttl-=dt);g.blasts=g.blasts.filter(b=>b.ttl>0);g.breakingBricks.forEach(b=>b.ttl-=dt);g.breakingBricks=g.breakingBricks.filter(b=>b.ttl>0);g.deadEnemies.forEach(e=>e.deadTimer-=dt);g.deadEnemies=g.deadEnemies.filter(e=>e.deadTimer>0);const trig=g.hazards.filter(h=>{h.ttl-=dt;return h.ttl<=0});g.hazards=g.hazards.filter(h=>h.ttl>0);for(const h of trig){g.blasts.push({...h,ttl:520,max:520,hostile:true,core:true,sourceId:'haz-'+BB.serial++});if(BB.same(h,g.player))BB.damagePlayer('blast')}g.powers.forEach(p=>p.phase+=dt*.005);if(g.exit)g.exit.phase+=dt*.006;g.enemies.forEach(e=>{e.rx=BB.lerp(e.rx,e.x,Math.min(1,dt*.014));e.ry=BB.lerp(e.ry,e.y,Math.min(1,dt*.014));e.frame+=dt*.01;e.hit=Math.max(0,e.hit-dt);e.attackTimer=Math.max(0,(e.attackTimer||0)-dt)});
if(g.time<=0&&g.pendingGameOver<=0){g.lives=0;BB.setPlayerAction('dead',900);g.pendingGameOver=900;BB.addText(g.player.x,g.player.y,'TEMPO ESGOTADO','#ffcf61')}
BB.explodeDue();BB.updateObjective(dt);const direction=BB.Input.dir();if(direction&&g.moveTimer<=0&&!BB.isPlayerBusy()){const [dx,dy]=BB.DIRS[direction],nx=g.player.x+dx,ny=g.player.y+dy;g.player.facing=direction;if(!BB.walkable(nx,ny,'','player'))BB.tryKick(nx,ny,dx,dy);if(BB.walkable(nx,ny,'','player')){g.player.x=nx;g.player.y=ny;g.moveTimer=g.moveDelay;BB.Audio.play('step',.08);BB.collectPower();if(g.exit&&BB.same(g.player,g.exit)&&!g.exit.locked){g.score+=Math.ceil(g.time/1000)*5;BB.grantReward();BB.finish(g.level>=BB.MAX_LEVEL?'completed':'won');return}else if(g.exit&&BB.same(g.player,g.exit)&&g.exit.locked)BB.addText(g.exit.x,g.exit.y,'PORTAL BLOQUEADO','#ff5578')}}
if(g.freeze<=0)for(const e of g.enemies){e.timer-=dt;e.special-=dt;if(e.boss&&e.special<=0){BB.bossAttack(e);e.special=Math.max(1000,3000-e.phase*350-BB.worldIndex(g.level)*150)}if(e.kind==='bomber'&&e.special<=0){BB.putBomb('enemy',e.x,e.y);e.special=3000}if(e.timer<=0){BB.enemyMove(e);const mult=e.kind==='tank'?1.35:e.kind==='hunter'?.9:e.kind==='ghost'?.95:e.boss?.8:1;e.timer=Math.max(190,(BB.CONFIG[BB.difficulty].delay-g.level*5)*mult)}}for(const e of [...g.enemies])for(const b of g.blasts)if(!b.hostile&&BB.same(e,b)){const dead=BB.damageEnemy(e,1,b.sourceId||('blast-'+b.x+'-'+b.y));if(dead){BB.killEnemy(e);g.score+=150}break}if(g.blasts.some(b=>BB.same(b,g.player))||g.enemies.some(e=>BB.same(e,g.player)))BB.damagePlayer(g.blasts.some(b=>BB.same(b,g.player))?'blast':'contact');BB.spawnExit();BB.UI.sync()};

BB.grantReward=function(){const g=BB.game;g.time+=5000;let reward='+5 SEGUNDOS';if(g.level%5===0){g.lives=BB.clamp(g.lives+1,1,7);g.speedLevel=BB.clamp(g.speedLevel+1,1,7);g.moveDelay=Math.max(72,150-(g.speedLevel-1)*12);reward='CHEFE: +1 VIDA E VELOCIDADE'}else if(g.level%4===0){g.maxBombs=BB.clamp(g.maxBombs+1,1,7);reward='NÚCLEO: +1 BOMBA'}else if(g.level%3===0){g.range=BB.clamp(g.range+1,2,9);reward='NÚCLEO: +1 ALCANCE'}g.lastReward=reward};
BB.resultData=function(){const g=BB.game,remaining=Math.ceil(g.time/1000),scoreBonus=remaining*5+g.stats.kills*50+g.stats.bricks*10+g.stats.maxCombo*100,total=g.score+scoreBonus;const grade=scoreBonus>1800?'S':scoreBonus>1100?'A':scoreBonus>650?'B':'C';return{remaining,kills:g.stats.kills,bricks:g.stats.bricks,powers:g.stats.powers,combo:g.stats.maxCombo,bonus:scoreBonus,total,grade}};
BB.restartLevel=function(){const g=BB.game;if(!g||g.status!=='playing')return;if(g.lives<=1){BB.finish('gameover');return}const carry={...g.entry,lives:g.lives-1,score:g.entry.score};BB.beginLevel(BB.makeGame(g.level,carry));BB.addText(1,1,'REINÍCIO: -1 VIDA','#ffcf61')};
